members/urls.py
from django.urls import path
from .views import MemberListView, MemberJoinView, MemberRegisterView, MemberLoginView, MemberStatusView, UserEditView, ProfileView, PasswordsChangeView, UserAddRoleView, UserNotificationsView
from .views import GroupListView, CreateGroupView, GroupEditView, GroupDeleteView, CreateGroupView, MemberEditGroupView, MemberEditPermissionView, UpdateProfilePictureView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('all', MemberListView.as_view(), name='member-list'),
    path('edit_group/<int:pk>/', MemberEditGroupView.as_view(), name='member-edit-group'),
    path('edit_permission/<int:pk>/', MemberEditPermissionView.as_view(), name='member-edit-permission'),
    path('status/<int:pk>/', MemberStatusView.as_view(), name='member-status'),
    path('groups/', GroupListView.as_view(), name='group-list'),
    path('groups/create/', CreateGroupView.as_view(), name='group-create'),
    path('groups/edit/<int:pk>', GroupEditView.as_view(), name='group-edit'),
    path('groups/delete/<int:group_id>', GroupDeleteView.as_view(), name='group-delete'),
    
    path('join/', MemberJoinView.as_view(), name='member-join'),
    path('register/', MemberRegisterView.as_view(), name='member-register'),
    path('login/', MemberLoginView.as_view(), name='member-login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('edit-profile/', UserEditView.as_view(), name='edit_profile'),
    path('additional-role/', UserAddRoleView.as_view(), name='additional_role'),
    path('update-profile-picture/', UpdateProfilePictureView.as_view(), name='update_profile_picture'),
    path('password/', PasswordsChangeView.as_view(template_name='members/change-password.html'), name='password_change'),
    path('notifications/', UserNotificationsView.as_view(), name='notifications'),
    
    path('password-reset/', auth_views.PasswordResetView.as_view(), name='reset_password'),
    path('password-reset-sent/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

posts/urls.py
from django.urls import path
from .views import SearchExplorePostView, SearchFeedPostView, SuscriberExplorePostsView, SuscriberFeedPostsView, SuscriberPostDetailView, UpdatePostsStatusView
from .views import CategoriesView, CategoryAddView, CategoryDetailView, CategoryEditView, CategoryDeleteView
from .views import ToEditView, ToEditPostView
from .views import ToPublishView, ToPublishPostView
from .views import MyPostsView, MyPostEditView, MyPostAddView, MyPostDeleteView
from .views import KanbanBoardView
from .views import HistoryView, ReportPostView, ReportedPostsView, TogglePostStatusView
from .views import RelevantPostsView
from .views import SubscribeView, UnsubscribeView, MyCategoriesView, CategoryDetailView


urlpatterns = [
    
    # urls for category administrators
    path('category/', CategoriesView.as_view(), name='categories'),
    path('category/add/', CategoryAddView.as_view(), name='category_add'),
    path('category/<int:pk>/<str:name>/', CategoryDetailView.as_view(), name='category'),
    path('category/<int:pk>/<str:name>/edit/', CategoryEditView.as_view(), name='category_edit'),
    path('category/<int:pk>/<str:name>/delete/', CategoryDeleteView.as_view(), name='category_delete'),
    
    # urls for suscribers
    path('all/search/', SearchExplorePostView.as_view(), name='post_search_explore'),
    path('feed/search/', SearchFeedPostView.as_view(), name='post_search_feed'),
    path('all/', SuscriberExplorePostsView.as_view(), name='posts'),
    path('feed/', SuscriberFeedPostsView.as_view(), name='feed'),
    path('<int:pk>/<slug:category>/<str:month>/<str:year>/<slug:title>/', SuscriberPostDetailView.as_view(), name='post'),
    path('<int:pk>/<slug:category>/<str:month>/<str:year>/<slug:title>/report/', ReportPostView.as_view(), name='report_post'),
    path('incidents/', ReportedPostsView.as_view(), name='incidents'),
    path('toggle-post-status/<int:pk>/', TogglePostStatusView.as_view(), name='toggle_post_status'),  


    # urls for authors
    path('my-posts/', MyPostsView.as_view(), name='my-posts'),
    path('my-posts/<int:pk>/', MyPostEditView.as_view(), name='edit-my-post'),
    path('my-posts/add/', MyPostAddView.as_view(), name='add-my-post'),
    path('my-posts/<int:pk>/delete/', MyPostDeleteView.as_view(), name='delete-my-post'),

    
    # urls for editors
    path('to-edit/', ToEditView.as_view(), name='to-edit'),
    path('to-edit/<int:pk>/', ToEditPostView.as_view(), name='edit-a-post'),
    
    # urls for publishers
    path('to-publish/', ToPublishView.as_view(), name='to-publish'),
    path('to-publish/<int:pk>/', ToPublishPostView.as_view(), name='publish-a-post'),

    # urls for kanban board
    path('kanban-board/', KanbanBoardView.as_view(), name='kanban-board'),
    path('update-posts-status/', UpdatePostsStatusView.as_view(), name='update-posts-status'),

    # urls for history
    path('<int:pk>/history/<int:history_id>/', HistoryView.as_view(), name='history'),

    # urls for relevant posts
    path('relevant-posts/', RelevantPostsView.as_view(), name='relevant-posts'),

    path('subscribe/<int:category_id>/', SubscribeView.as_view(), name='subscribe'),
    path('unsubscribe/<int:category_id>/', UnsubscribeView.as_view(), name='unsubscribe'),
    path('my-categories/', MyCategoriesView.as_view(), name='my_categories'),
]

weblio/urls.py
from django.contrib import admin
from django.urls import path, include
from members.views import HomeView
from django.conf import settings
from django.conf.urls.static import static
from ckeditor_uploader.views import ImageUploadView
from members.views import Error404View, Error500View, Error403View


# Se configuran las URL de la aplicacion
urlpatterns = [
    path('admin/', admin.site.urls),
    path('members/', include('members.urls')),
    path('posts/', include('posts.urls')),
    path('', HomeView.as_view(), name='home'),
]

# Se configuran las URLs de los servicios externos segun el entorno
if settings.DEBUG:
    urlpatterns += [
        
        # URLs for ckeditor (development)
        path("ckeditor/", include('ckeditor_uploader.urls')),
        path('ckeditor/upload/', ImageUploadView.as_view(), name='ckeditor_upload'),

        # URLs for stripe (development)
        path('stripe/create-checkout-session/<int:category_id>/', HomeView.as_view(), name='stripe_checkout'),
        path('stripe/payment-success/', HomeView.as_view(), name='payment_success'),
        path('stripe/payment-cancel/<int:category_id>/', HomeView.as_view(), name='payment_cancel'),

        # urls for stats of engagement
        path('stats/engagement/dashboard', HomeView.as_view(), name='engagement_dashboard'),
        path('stats/engagement/posts/views/', HomeView.as_view(), name='posts_claps'),
        path('stats/engagement/posts/likes/', HomeView.as_view(), name='posts_updowns'),
        path('stats/engagement/posts/stars/', HomeView.as_view(), name='posts_rates'),
        path('stats/engagement/categories/views/', HomeView.as_view(), name='categories_claps'),
        path('stats/engagement/categories/likes/', HomeView.as_view(), name='categories_updowns'),
        path('stats/engagement/categories/stars/', HomeView.as_view(), name='categories_rates'),

        # urls for stats of finances
        path('stats/finances/dashboard/', HomeView.as_view(), name='finances_dashboard'),
        path('stats/finances/posts/', HomeView.as_view(), name='members_finances'),
        path('stats/finances/categories/', HomeView.as_view(), name='categories_finances'),

        # urls for member purchase
        path('member-purchase/', HomeView.as_view(), name='member_purchase'),

        # URLs for password reset email (development)
        path('members/reset_password/', HomeView.as_view(), name='reset_password_email'),
        path('members/password_reset_done/', HomeView.as_view(), name='password_reset_done_email'),
        path('members/password_reset_confirm/', HomeView.as_view(), name='password_reset_confirm_email'),
        path('members/password_reset_complete/', HomeView.as_view(), name='password_reset_complete_email'),

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
else:
    urlpatterns += [
        path("services/", include('services.urls')),
    ]

# Se configuran las vistas de error
handler404 = Error404View.as_view()
handler500 = Error500View.as_view()
handler403 = Error403View.as_view()

members/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils.translation import gettext_lazy as _
from .managers import MemberManager

class Member(AbstractBaseUser, PermissionsMixin):
    """
    Modelo de usuario personalizado donde el email es el identificador único
    para la autenticación.

    Hereda de:
        - AbstractBaseUser: Proporciona las implementaciones principales para un modelo de usuario.
        - PermissionsMixin: Agrega campos y métodos de permisos al modelo de usuario.

    Atributos:
        username (CharField): Nombre de usuario único.
        first_name (CharField): Primer nombre del usuario.
        last_name (CharField): Apellido del usuario.
        email (EmailField): Dirección de email del usuario. Es el identificador único.
        is_active (BooleanField): Indica si el usuario está activo.
        is_staff (BooleanField): Indica si el usuario puede acceder al sitio de administración.
        date_joined (DateTimeField): La fecha y hora en que el usuario se unió.
        pfp (ImageField): Imagen de perfil del usuario.
        purchased_categories (ManyToManyField): Categorías compradas por el usuario.
        suscribed_categories (ManyToManyField): Categorías a las que el usuario está suscrito.

    Atributos de clase:
        USERNAME_FIELD (str): Define el campo que se usa como identificador único (username).
        REQUIRED_FIELDS (list): Lista de campos obligatorios para el usuario, además de USERNAME_FIELD.
        objects (MemberManager): El gestor de modelos personalizado para manejar la creación de usuarios y superusuarios.

    Métodos:
        __str__(): Retorna el username del usuario como representación en cadena.
        get_pfp_url(): Retorna la URL de la imagen de perfil del usuario o una URL por defecto si no tiene imagen.
    """

    username = models.CharField(max_length=150, unique=True, default = '')
    first_name = models.CharField(_('first name'), max_length=30, default = '')
    last_name = models.CharField(_('last name'), max_length=150, default = '')
    email = models.EmailField(_('email address'), unique=True)
    is_active = models.BooleanField(_('active'), default=True)
    is_staff = models.BooleanField(_('staff status'), default=True)
    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)
    pfp = models.ImageField(upload_to='profile_pictures/', blank=True, null=True)
    purchased_categories = models.ManyToManyField('posts.Category', related_name='purchased_members', blank=True)
    suscribed_categories = models.ManyToManyField('posts.Category', related_name='suscribed_members', blank=True)


    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email' ,'first_name', 'last_name']

    objects = MemberManager()

    class Meta:
        verbose_name = _('member')
        verbose_name_plural = _('members')

        permissions = [
            ('view_dashboard', 'Can view dashboard'),
            ('make_relevant', 'Can make a post relevant'),
            ('auto_publish', 'Puede auto-publicar artículo'),
            ('view_finances', 'Puede ver las finanzas'),
        ]

    def __str__(self):
        """
        Retorna la representación en cadena del usuario.

        Retorna:
            str: El username del usuario.
        """
        return self.username
    
    def get_pfp_url(self):
        """
        Retorna la URL de la imagen de perfil del usuario o una URL por defecto si no tiene imagen.

        Retorna:
            str: La URL de la imagen de perfil del usuario o una URL por defecto.
        """
        if self.pfp:
            return self.pfp.url
        return 'https://picsum.photos/seed/picsum/1080'  # URL de imagen por defecto
    
class Notification(models.Model):
    """
    Clase Notification que representa las notificaciones de un usuario.

    Atributos:
        user (ForeignKey): Referencia al modelo Member, con eliminación en cascada.
        notifications (ManyToManyField): Relación con el modelo 'posts.Category', con nombre relacionado 'notificaciones' y opcional.
        additional_notifications (JSONField): Campo JSON para notificaciones adicionales, con valor por defecto una lista vacía.
        receive (BooleanField): Indica si el usuario desea recibir notificaciones, por defecto True.

    Métodos:
        __str__(): Retorna una cadena representativa de las notificaciones del usuario.
        get_additional_notifications(): Retorna una lista de notificaciones adicionales basadas en los permisos del usuario.
    """
    user = models.ForeignKey(Member, on_delete=models.CASCADE)
    notifications = models.ManyToManyField('posts.Category', related_name='notificaciones', blank=True)
    additional_notifications = models.JSONField(default=list)
    receive = models.BooleanField(default=True)

    def __str__(self):
        """
        Devuelve una representación en cadena de la instancia del modelo.

        Returns:
            str: Una cadena que representa las notificaciones del usuario.
        """
        return f'Notificaciones de {self.user.username}'

    def get_additional_notifications(self):
        """
        Obtiene una lista de notificaciones adicionales basadas en los permisos del usuario.

        Returns:
            list: Una lista de cadenas que representan notificaciones adicionales.
        """
        additional_notifications = [
            'Informar sobre inicio de sesión',
            'Informar sobre actualización de permisos',
            'Informar sobre activación/inactivación de cuenta'
        ]

        permissions_list = [
            'posts.add_post',
            'posts.change_post',
            'posts.can_publish',
            'posts.delete_post'
        ]
        if any(self.user.has_perm(perm) for perm in permissions_list):
            additional_notifications.append('Informar sobre cambios de estado de articulos')

        return additional_notifications

members/templates/CSSLibraries.html
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-table@1.23.4/dist/bootstrap-table.min.css">

<!-- Font Awesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

members/templates/JSlibraries.html
<!-- Bootstrap JS and dependencies -->
<script src="https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>

<!-- Bootstrap Table core -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap-table@1.23.4/dist/bootstrap-table.min.js"></script>

<!-- Locale for Bootstrap Table (Spanish) -->
<script src="https://unpkg.com/bootstrap-table@1.21.1/dist/locale/bootstrap-table-es-ES.min.js"></script>

<!-- Include Bootstrap Table Export Scripts -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap-table/dist/extensions/export/bootstrap-table-export.min.js"></script>

<!-- Export functionality: FileSaver, jsPDF, and TableExport -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/2.0.5/FileSaver.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jsPDF/2.3.1/jspdf.umd.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jsPDF-AutoTable/3.5.25/jspdf.plugin.autotable.min.js"></script> <!-- Ensure this is included -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.16.9/xlsx.core.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/tableexport.jquery.plugin/tableExport.min.js"></script>

<!-- Masonry JS -->
<script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
<script src="https://unpkg.com/imagesloaded@4/imagesloaded.pkgd.min.js"></script>

members/templates/base.html
{% load custom_filters %}
{% load static %}
<!doctype html>
<html lang="en" class="bg-dark text-white">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}Weblio{% endblock %}</title>
        <link rel="icon" type="image/png" href="https://storage.googleapis.com/bucket-weblio/branding/logo/logo-small.png">

        <!-- CSS Libraries -->
        {% include "CSSLibraries.html" %}

        <!-- Custom CSS -->
        {% include "styles.html" %}
    </head>
    <body>
        <!-- Navbar -->
        {% include "navbar.html" %}

        <!-- Spinner Overlay -->
        {% include "spinner.html" %}

        <!-- Popup de mensajes (errores, advertencias) -->
        {% include "popup.html" %}

        <!-- Django block content -->
        <main class="bg-dark text-white">
            {% block content %}{% endblock %}
        </main>

        <!-- Footer -->
        <footer class="py-2">
            <div class="container">
            <p class="mb-0">Desarrollado con <span class="heart">❤️</span> (y <span class="coffee">☕</span>) por el equipo de Weblio &copy;</p>
            </div>
        </footer>

        <!-- JS Libraries -->
        {% include "JSlibraries.html" %}
    </body>
</html>

members/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary sticky-top" data-bs-theme="dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">
            <img src="https://storage.googleapis.com/bucket-weblio/branding/logo/logo-small.png" alt="Weblio Logo" height="30" class="d-inline-block align-text-top me-2">
            Weblio
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <!-- Artículos -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Artículos
                    </a>
                    <ul class="dropdown-menu">
                        {% if user.is_authenticated and perms.posts.view_post %}
                            <li><a class="dropdown-item" href="{% url 'feed' %}">Mis artículos</a></li>
                            <li><hr class="dropdown-divider"></li>
                        {% endif %}
                        <li><a class="dropdown-item" href="{% url 'posts' %}">Explorar artículos</a></li>
                    </ul>
                </li>

                <!-- Categorías -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Categorías
                    </a>
                    <ul class="dropdown-menu">
                        {% if user.is_authenticated and perms.posts.view_post %}
                        <li><a class="dropdown-item" href="{% url 'my_categories' %}">Mis categorías</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'member_purchase' %}">Mis compras</a></li>
                        <li><hr class="dropdown-divider"></li>
                        {% endif %}
                        <li><a class="dropdown-item" href="{% url 'categories' %}">Explorar categorías</a></li>
                        {% if perms.posts.add_category %}
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'category_add' %}">Nueva Categoría</a></li>
                        {% endif %}
                    </ul>
                </li>

                <!-- Gestión de contenido -->
                {% if perms.posts.add_post or perms.posts.change_post or perms.posts.can_publish %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Contenido
                        </a>
                        <ul class="dropdown-menu">
                            {% if perms.posts.add_post %}
                                <li><a class="dropdown-item" href="{% url 'my-posts' %}">Mis Artículos</a></li>
                                <li><a class="dropdown-item" href="{% url 'add-my-post' %}">Crear un artículo</a></li>
                            {% endif %}
                            {% if perms.posts.change_post %}
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="{% url 'to-edit' %}">Artículos a editar</a></li>
                            {% endif %}
                            {% if perms.posts.can_publish %}
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="{% url 'to-publish' %}">Artículos a publicar</a></li>
                            {% endif %}
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'kanban-board' %}">Tablero Kanban</a></li>
                            {% if perms.members.make_relevant %}
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="{% url 'relevant-posts' %}">Artículos relevantes</a></li>
                            {% endif %}
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'incidents' %}">Incidencias</a></li>
                        </ul>
                    </li>
                {% endif %}

                <!-- Gestión de usuarios -->
                {% if perms.auth.change_member %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Usuarios
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'member-list' %}">Mostrar usuarios</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'group-list' %}">Mostrar roles</a></li>
                            <li><a class="dropdown-item" href="{% url 'group-create' %}">Crear rol</a></li>
                        </ul>
                    </li>
                {% endif %}
                <!-- Gestión de reportes -->
                {% if perms.posts.add_post or perms.posts.change_post or perms.posts.can_publish or perms.members.view_dashboard %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Reportes
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'posts_claps' %}">Vistas por artículo</a></li>
                            <li><a class="dropdown-item" href="{% url 'posts_updowns' %}">Likes/Dislikes por artículo</a></li>
                            <li><a class="dropdown-item" href="{% url 'posts_rates' %}">Estrellas por artículo</a></li>
                            <li><hr class="dropdown-divider"></li>
                            {% if perms.posts.change_post or perms.posts.can_publish or perms.members.view_dashboard %}
                                <li><a class="dropdown-item" href="{% url 'categories_claps' %}">Vistas por categoría</a></li>
                                <li><a class="dropdown-item" href="{% url 'categories_updowns' %}">Likes/Dislikes por categoría</a></li>
                                <li><a class="dropdown-item" href="{% url 'categories_rates' %}">Estrellas por categoría</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="{% url 'engagement_dashboard' %}">Dashboard</a></li>
                            {% endif %}
                        </ul>
                    </li>
                {% endif %}
                
                <!-- Gestión de finanzas -->
                {% if perms.members.view_finances %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Finanzas
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'members_finances' %}">Reporte de ventas</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'finances_dashboard' %}">Dashboard</a></li>
                        </ul>
                    </li>
                {% endif %}
            </ul>

            <!-- Barra de búsqueda -->
            {% if request.path == '/posts/all/' or request.path == '/posts/all/search/' or request.path == '/posts/feed/' or request.path == '/posts/feed/search/' %}
                <form method="GET" action=" {% if request.path == '/posts/all/' or request.path == '/posts/all/search/' %}
                                                {% url 'post_search_explore' %}
                                            {% elif request.path == '/posts/feed/' or request.path == '/posts/feed/search/' %}
                                                {% url 'post_search_feed' %}
                                            {% endif %}" class="d-flex flex-grow-1 me-4" role="search">
                <input class="form-control bg-dark text-white me-2" type="search" placeholder="Buscar" aria-label="Search" name="q">
                <button class="btn btn-outline-success text-white" type="submit">Buscar</button>
                </form>
            {% endif %}

            <!-- Botones de inicio de sesión / perfil -->
            <div class="d-flex align-items-center ms-lg-3 mt-2 mt-lg-0">
                {% if not user.is_authenticated %}
                    <a class="btn btn-primary px-3 me-2" href="{% url 'member-login' %}">Iniciar Sesión</a>
                    <a class="btn btn-outline-secondary px-3" href="{% url 'member-register' %}">Registrarse</a>
                {% else %}
                    <div class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle d-flex align-items-center" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            {% if user.pfp %}
                                <img src="{{ user.pfp.url }}" height="40px" width="40px" alt="User Image" class="rounded-circle me-2">
                            {% else %}
                                <img src="https://storage.googleapis.com/bucket-weblio/media/profile_pictures/default_pfp.jpg" height="40px" width="40px" alt="Default User Image" class="rounded-circle me-2">
                            {% endif %}
                            {{ user.first_name }} {{ user.last_name }}
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end">
                            <li><a class="dropdown-item" href="{% url 'profile' %}">Perfil</a></li>
                            <li><a class="dropdown-item" href="{% url 'edit_profile' %}">Editar Perfil</a></li>
                            <li><a class="dropdown-item" href="{% url 'notifications' %}">Configuración</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li>
                                <form method="POST" action="{% url 'logout' %}">
                                    {% csrf_token %}
                                    <button type="submit" class="dropdown-item">Cerrar Sesión</button>
                                </form>
                            </li>
                        </ul>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</nav>

members/templates/popup.html
<div class="container">
    {% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show alert-fixed" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
    {% endif %}
</div>
<script>
    setTimeout(function() {
    document.querySelectorAll('.alert-fixed').forEach(function(alert) {
        alert.remove();
    });
    }, 5000);
</script>