posts/urls.py
from django.urls import path
from .views import SearchExplorePostView, SearchFeedPostView, SuscriberExplorePostsView, SuscriberFeedPostsView, SuscriberPostDetailView, UpdatePostsStatusView
from .views import CategoriesView, CategoryAddView, CategoryDetailView, CategoryEditView, CategoryDeleteView
from .views import ToEditView, ToEditPostView
from .views import ToPublishView, ToPublishPostView
from .views import MyPostsView, MyPostEditView, MyPostAddView, MyPostDeleteView
from .views import KanbanBoardView
from .views import HistoryView, ReportPostView, ReportedPostsView, TogglePostStatusView
from .views import RelevantPostsView
from .views import SubscribeView, UnsubscribeView, MyCategoriesView, CategoryDetailView


urlpatterns = [
    
    # urls for category administrators
    path('category/', CategoriesView.as_view(), name='categories'),
    path('category/add/', CategoryAddView.as_view(), name='category_add'),
    path('category/<int:pk>/<str:name>/', CategoryDetailView.as_view(), name='category'),
    path('category/<int:pk>/<str:name>/edit/', CategoryEditView.as_view(), name='category_edit'),
    path('category/<int:pk>/<str:name>/delete/', CategoryDeleteView.as_view(), name='category_delete'),
    
    # urls for suscribers
    path('all/search/', SearchExplorePostView.as_view(), name='post_search_explore'),
    path('feed/search/', SearchFeedPostView.as_view(), name='post_search_feed'),
    path('all/', SuscriberExplorePostsView.as_view(), name='posts'),
    path('feed/', SuscriberFeedPostsView.as_view(), name='feed'),
    path('<int:pk>/<slug:category>/<str:month>/<str:year>/<slug:title>/', SuscriberPostDetailView.as_view(), name='post'),
    path('<int:pk>/<slug:category>/<str:month>/<str:year>/<slug:title>/report/', ReportPostView.as_view(), name='report_post'),
    path('incidents/', ReportedPostsView.as_view(), name='incidents'),
    path('toggle-post-status/<int:pk>/', TogglePostStatusView.as_view(), name='toggle_post_status'),  


    # urls for authors
    path('my-posts/', MyPostsView.as_view(), name='my-posts'),
    path('my-posts/<int:pk>/', MyPostEditView.as_view(), name='edit-my-post'),
    path('my-posts/add/', MyPostAddView.as_view(), name='add-my-post'),
    path('my-posts/<int:pk>/delete/', MyPostDeleteView.as_view(), name='delete-my-post'),

    
    # urls for editors
    path('to-edit/', ToEditView.as_view(), name='to-edit'),
    path('to-edit/<int:pk>/', ToEditPostView.as_view(), name='edit-a-post'),
    
    # urls for publishers
    path('to-publish/', ToPublishView.as_view(), name='to-publish'),
    path('to-publish/<int:pk>/', ToPublishPostView.as_view(), name='publish-a-post'),

    # urls for kanban board
    path('kanban-board/', KanbanBoardView.as_view(), name='kanban-board'),
    path('update-posts-status/', UpdatePostsStatusView.as_view(), name='update-posts-status'),

    # urls for history
    path('<int:pk>/history/<int:history_id>/', HistoryView.as_view(), name='history'),

    # urls for relevant posts
    path('relevant-posts/', RelevantPostsView.as_view(), name='relevant-posts'),

    path('subscribe/<int:category_id>/', SubscribeView.as_view(), name='subscribe'),
    path('unsubscribe/<int:category_id>/', UnsubscribeView.as_view(), name='unsubscribe'),
    path('my-categories/', MyCategoriesView.as_view(), name='my_categories'),
]

weblio/urls.py
from django.contrib import admin
from django.urls import path, include
from members.views import HomeView
from django.conf import settings
from django.conf.urls.static import static
from ckeditor_uploader.views import ImageUploadView
from members.views import Error404View, Error500View, Error403View


# Se configuran las URL de la aplicacion
urlpatterns = [
    path('admin/', admin.site.urls),
    path('members/', include('members.urls')),
    path('posts/', include('posts.urls')),
    path('', HomeView.as_view(), name='home'),
]

# Se configuran las URLs de los servicios externos segun el entorno
if settings.DEBUG:
    urlpatterns += [
        
        # URLs for ckeditor (development)
        path("ckeditor/", include('ckeditor_uploader.urls')),
        path('ckeditor/upload/', ImageUploadView.as_view(), name='ckeditor_upload'),

        # URLs for stripe (development)
        path('stripe/create-checkout-session/<int:category_id>/', HomeView.as_view(), name='stripe_checkout'),
        path('stripe/payment-success/', HomeView.as_view(), name='payment_success'),
        path('stripe/payment-cancel/<int:category_id>/', HomeView.as_view(), name='payment_cancel'),

        # urls for stats of engagement
        path('stats/engagement/dashboard', HomeView.as_view(), name='engagement_dashboard'),
        path('stats/engagement/posts/views/', HomeView.as_view(), name='posts_claps'),
        path('stats/engagement/posts/likes/', HomeView.as_view(), name='posts_updowns'),
        path('stats/engagement/posts/stars/', HomeView.as_view(), name='posts_rates'),
        path('stats/engagement/categories/views/', HomeView.as_view(), name='categories_claps'),
        path('stats/engagement/categories/likes/', HomeView.as_view(), name='categories_updowns'),
        path('stats/engagement/categories/stars/', HomeView.as_view(), name='categories_rates'),

        # urls for stats of finances
        path('stats/finances/dashboard/', HomeView.as_view(), name='finances_dashboard'),
        path('stats/finances/posts/', HomeView.as_view(), name='members_finances'),
        path('stats/finances/categories/', HomeView.as_view(), name='categories_finances'),

        # urls for member purchase
        path('member-purchase/', HomeView.as_view(), name='member_purchase'),

        # URLs for password reset email (development)
        path('members/reset_password/', HomeView.as_view(), name='reset_password_email'),
        path('members/password_reset_done/', HomeView.as_view(), name='password_reset_done_email'),
        path('members/password_reset_confirm/', HomeView.as_view(), name='password_reset_confirm_email'),
        path('members/password_reset_complete/', HomeView.as_view(), name='password_reset_complete_email'),

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
else:
    urlpatterns += [
        path("services/", include('services.urls')),
    ]

# Se configuran las vistas de error
handler404 = Error404View.as_view()
handler500 = Error500View.as_view()
handler403 = Error403View.as_view()

posts/models.py
from django.db import models
from django.utils import lorem_ipsum
from django.urls import reverse
from django.utils.text import slugify
from django.core.validators import MinValueValidator
from members.models import Member
from ckeditor_uploader.fields import RichTextUploadingField
from members.models import Member
import requests
from simple_history.models import HistoricalRecords
from django.utils import timezone
from django.template.loader import render_to_string
from django.core.mail import EmailMultiAlternatives
from django.contrib.sites.models import Site
from django.conf import settings
from django.apps import apps

# Create your models here.
class Category(models.Model):
    """
    Representa una categoría que agrupa diferentes publicaciones.

    Atributos:
    ----------
    name : str
        Nombre de la categoría.
    description : str
        Descripción corta de la categoría.
    alias : str
        Alias o abreviatura de la categoría.
    price : Decimal
        Precio asociado a la categoría, con un valor mínimo de 0.00.
    kind : str
        Tipo de categoría, puede ser 'public', 'free' o 'premium'.
    moderated : bool
        Indica si la categoría está moderada.

    Métodos:
    --------
    __str__():
        Retorna una representación legible de la categoría, incluyendo su nombre y tipo.
    get_absolute_url():
        Devuelve la URL canónica para una instancia específica de la categoría.
    """

    name = models.CharField(max_length=100)
    description = models.CharField(max_length=100, default=lorem_ipsum.words(10))
    alias = models.CharField(max_length=2, default='')
    price = models.DecimalField(max_digits=6, decimal_places=2, default=0.00, validators=[MinValueValidator(0.00)], null=True, blank=True)
    kind = models.CharField(max_length=20, choices=(('public', 'Public'), ('free', 'Free'), ('premium', 'Premium'),), default='free')
    moderated = models.BooleanField(default=True)

    def __str__(self):
        """Retorna el nombre de la categoría junto con su tipo."""
        return f"{self.name} ({self.kind})" + (" (No moderada)" if not self.moderated else "")
    
    def get_absolute_url(self):
        """
        Devuelve la URL canónica para la categoría.

        Returns:
            str: URL para acceder a la categoría.
        """
        return reverse('category', args=[
            self.pk,
            slugify(self.name)])

def get_default_category():
    """
    Obtiene o crea la categoría por defecto 'Uncategorized'.

    Returns:
    --------
    int
        ID de la categoría por defecto.
    """
    return Category.objects.get_or_create(name='Uncategorized')[0].id

def get_lorem_ipsum_text():
    """
    Obtiene texto de ejemplo de la API de Loripsum.

    Returns:
    --------
    str
        Texto de ejemplo obtenido de la API.
    """
    response = requests.get('https://loripsum.net/api/15/long/headers/decorate/link/ul/ol/dl/bq/code')
    if response.status_code == 200:
        return response.text
    return ''

class Post(models.Model):
    """
    Representa una publicación o artículo que pertenece a una categoría.

    Atributos:
    ----------
    title : str
        Título del post.
    title_tag : str
        Etiqueta del título para SEO.
    summary : str
        Resumen breve del post.
    body : str
        Contenido principal del post, que soporta texto enriquecido.
    date_posted : datetime
        Fecha y hora en que se creó el post.
    author : Member
        Autor del post, relacionado con un usuario.
    status : str
        Estado actual del post ('draft', 'to_edit', 'to_publish', 'published').
    category : Category
        Categoría a la que pertenece el post.
    keywords : str
        Palabras clave asociadas al post para SEO.
    thumbnail : ImageField
        Miniatura de la publicación.
    publish_start_date : datetime
        Fecha de inicio de publicación.
    publish_end_date : datetime
        Fecha de fin de publicación.
    change_reason : str
        Razón del cambio.
    priority : int
        Prioridad del post.
    
    Métodos:
    --------
    __str__():
        Retorna una representación legible del post, incluyendo el título y el autor.
    get_absolute_url():
        Devuelve la URL canónica para una instancia específica del post.
    calculate_priority():
        Calcula la prioridad del post basado en el tipo de categoría (kind).
    save(*args, **kwargs):
        Sobrescribe el método save para establecer date_posted cuando el estado cambia a 'published'.
    send_status_change_email(old_status):
        Envía un correo electrónico notificando el cambio de estado del post.
    get_status_display(status_value):
        Traduce el valor del estado a una versión legible (en español).

    Meta:
    -----
    permissions : list
        Lista de permisos personalizados para el modelo.
    """

    title = models.CharField(max_length=100)
    title_tag = models.CharField(max_length=100)
    summary = models.CharField(max_length=100, default=lorem_ipsum.words(10)) 
    body = RichTextUploadingField('Text', blank=True, default=get_lorem_ipsum_text)
    date_posted = models.DateTimeField(blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    author = models.ForeignKey(Member, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=(('draft', 'Draft'), ('to_edit', 'To Edit'), ('to_publish', 'To Publish'), ('published', 'Published'), ('inactive', 'Inactive')), default='draft')
    category = models.ForeignKey(Category, on_delete=models.SET_DEFAULT, default=get_default_category)
    keywords = models.CharField(max_length=100, blank=True, null=True)
    history = HistoricalRecords()
    thumbnail = models.ImageField(upload_to='thumbnails/', blank=True, null=True)
    publish_start_date = models.DateTimeField(blank=True, null=True)
    publish_end_date = models.DateTimeField(blank=True, null=True)
    change_reason = models.CharField(max_length=255, blank=True, null=True)
    thumbnail = models.ImageField(upload_to='thumbnails/', blank=True, null=True)
    priority = models.IntegerField(blank=True, null=True)

    class Meta:
        permissions = [
            ('can_publish', 'Can publish post'),
        ]

    def __str__(self):
        """Retorna el título del post junto con el nombre del autor."""
        return self.title + ' | ' + str(self.author)
    
    def get_absolute_url(self):
        """
        Devuelve la URL canónica para el post.

        Returns:
            str: URL para acceder al post.
        """
        return reverse('post', args=[
            self.pk,
            slugify(self.category.name),
            self.date_posted.strftime('%m'),
            self.date_posted.strftime('%Y'),
            slugify(self.title)
        ])
    
    def calculate_priority(self):
        """
        Calcula la prioridad del post basado en el tipo de categoría (kind).

        1: public
        2: free
        3: premium
        """
        if self.category.kind == 'public':
            return 1
        elif self.category.kind == 'free':
            return 2
        elif self.category.kind == 'premium':
            return 3
        return None
    
    def save(self, *args, from_kanban=False, **kwargs):
        """
        Sobrescribe el método save para establecer date_posted cuando el estado cambia a 'published'.
        """
        # Establecer la fecha de publicación si el estado es 'published' y la fecha de publicación es nula
        if self.status == 'published' and self.date_posted is None:
            self.date_posted = timezone.now()
        
        # Verificar si el status ha cambiado
        old_status = None
        if self.pk:
            old_post = Post.objects.get(pk=self.pk)
            old_status = old_post.status

        # Calcular la prioridad antes de guardar
        self.priority = self.calculate_priority() if self.priority != 4 else self.priority

        super().save(*args, **kwargs)

        # Enviar correo si el estado ha cambiado
        if old_status != self.status or from_kanban:
            self.send_status_change_email(old_status)

    def send_status_change_email(self, old_status):
        """
        Envía un correo electrónico notificando el cambio de estado del post.

        Args:
        -----
        old_status : str
            Estado anterior del post.

        Returns:
        --------
        None
        """
        # Recuperar el último historial
        last_history = self.history.order_by('-history_date').first()
        changed_by = last_history.history_user
        change_reason = self.change_reason or "Sin razón proporcionada"
        change_date = last_history.history_date

        # Crear la URL absoluta del post
        current_site = Site.objects.get_current()

        # Ajusta el dominio y el protocolo del sitio según la configuración
        current_site.domain = settings.SITE_DOMAIN
        site_protocol = settings.SITE_PROTOCOL


        # Obtener el estado anterior y el nuevo estado con traducción
        old_status_translated = self.get_status_display(old_status)
        new_status_translated = self.get_status_display(self.status)

        # Preparar el contexto para el correo
        context = {
            'post': self,
            'old_status': old_status_translated,
            'new_status': new_status_translated,
            'changed_by': changed_by,
            'change_reason': change_reason,
            'change_date': change_date,
        }

        # Obtener el modelo de usuario personalizado
        User = apps.get_model(settings.AUTH_USER_MODEL)

        # Obtener la lista de usuarios a notificar
        users_to_notify = set()

        # Autor del post
        author_notification = self.author.notification_set.first()
        if author_notification and 'Informar sobre cambios de estado de articulos' in author_notification.additional_notifications:

posts/templates/categories/categories.html
{% extends "base.html" %}
{% block content %}
<main role="main" class="container py-4">
    <h1>Categorías</h1>
    
    <!-- Ajustamos el diseño grid para que sea responsive -->
    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
        {% for category in object_list %}
        <div class="col">
            <a class="card-link" href="{% url 'category' pk=category.pk name=category.name|slugify %}">
            <div class="card card-hover custom-card mb-3 h-100">
                <div class="card-body d-flex flex-column">
                    <div class="d-flex justify-content-between align-items-center">
                        <!-- Título de la categoría -->
                        <h5 class="card-title category-title">{{ category.name }}</h5>
                        <!-- Insignia del tipo de categoría -->
                        {% if category.kind == 'free' %}
                            <span class="badge badge-free">
                                <i class="bi bi-gift"></i> Gratis
                            </span>
                        {% elif category.kind == 'public' %}
                            <span class="badge badge-public">
                                <i class="bi bi-globe"></i> Público
                            </span>
                        {% elif category.kind == 'premium' %}
                            <span class="badge badge-premium">
                                <i class="bi bi-star"></i> Premium
                            </span>
                        {% endif %}
                    </div>

                    <!-- Descripción de la categoría -->
                    <p class="card-text flex-grow-1">{{ category.description|safe }}</p>
                </div>
            </div>
            </a>
        </div>
        {% endfor %}
    </div>
</main>
<style>
    .custom-card{
        background-color: #343a40; /* Fondo oscuro */
        color: #ffffff; /* Texto blanco */
        border: none; /* Sin borde */
        border-radius: 0.5rem; /* Bordes redondeados */
    }
    /* Estilos personalizados para las insignias minimalistas */
    .badge {
        font-size: 0.9rem;
        padding: 0.2em 0.4em;
        border-radius: 0.2rem;
    }
    /* Colores minimalistas y suaves para las diferentes etiquetas */
    .badge-free {
        background-color: #e6f5ea; /* Verde grisáceo suave */
        color: #2d6a4f; /* Verde oscuro */
    }
    .badge-public {
        background-color: #e7f0fa; /* Azul grisáceo suave */
        color: #1e3a8a; /* Azul oscuro */
    }
    .badge-premium {
        background-color: #fff8e5; /* Amarillo grisáceo suave */
        color: #7d5800; /* Marrón oscuro */
    }

    /* Contador de publicaciones como texto sin fondo */
    .category-count {
        color: #ffffff; /* Color blanco para que destaque en el fondo oscuro */
        font-weight: 400;
        font-size: 0.9rem;
    }

    /* Aumentando el espacio entre el nombre de la categoría y el badge del tipo */
    .ml-3 {
        margin-left: 0.75rem !important; /* Ajuste del margen izquierdo */
    }

    .card-title {
        color: #007bff;
    }

    /* Make the entire card clickable */
    .card-link {
        text-decoration: none;
        color: inherit;
    }

    .card-link:hover .category-title {
        color: #007bff; /* Blue on hover */
        text-decoration: underline;
    }

    /* Hover effect to enlarge the card */
    .card-hover {
        transition: transform 0.3s ease;
    }

    .card-hover:hover {
        transform: scale(1.05); /* Slightly enlarge the card on hover */
    }
</style>
{% endblock %}

posts/templates/categories/category.html
{% extends "base.html" %}
{% block content %}
    <main role="main" class="container py-4">
            
        <!-- Detalles de la categoría -->
        <h1>
            {{ category.name }} - {{ category.alias }}
            {% if category.moderated %}
                <!-- Explicación del estado Moderada (usamos bi-shield-fill-check para algo más llamativo) -->
                <div class="d-inline-block position-relative mx-3">
                    <i class="bi bi-shield-fill-check text-success fs-1" data-bs-toggle="tooltip" data-bs-placement="top" title="Moderada: El contenido de esta categoría ha sido editado, revisado y publicado por nuestro equipo."></i>
                </div>
            {% else %}
                <!-- Explicación del estado No Moderada (usamos bi-exclamation-triangle-fill para algo más visible en amarillo) -->
                <div class="d-inline-block position-relative mx-3">
                    <i class="bi bi-exclamation-triangle-fill text-warning fs-1" data-bs-toggle="tooltip" data-bs-placement="top" title="No Moderada: El contenido de esta categoría no ha sido revisado por nuestro equipo y fue publicado directamente por el autor."></i>
                </div>
            {% endif %}
        </h1>
        <hr>
        <h2>Tipo: {{ category.kind }}</h2>
        <h2>Precio: {{ category.price }}</h2>
        <p>{{ category.description }}</p>

        <!-- Botones de acciones -->
        <div class="d-flex flex-column flex-md-row gap-2">
            <a href="{{ next_url|default:'/posts/category/' }}" class="btn btn-primary">Volver</a>

            {% if category.kind != 'premium' and perms.posts.view_post %}
                {% if category in request.user.suscribed_categories.all %}
                    <form method="post" action="{% url 'unsubscribe' category.id %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Desuscribirse</button>
                    </form>
                {% else %}
                    <form method="post" action="{% url 'subscribe' category.id %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-success">Suscribirse</button>
                    </form>
                {% endif %}
            {% endif %}

            {% if perms.posts.change_category %}
                <a href="{% url 'category_edit' pk=category.pk name=category.name|slugify %}" class="btn btn-warning">Editar</a>
            {% endif %}

            {% if perms.posts.delete_category %}
                <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal">Eliminar</button>
            {% endif %}
        </div>

        <!-- Modal de eliminación -->
        <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content" style="background-color: white; color: black;">
                    {% if category_count == 1 %}
                        <div class="modal-header" style="color: black;">
                            <h5 class="modal-title" id="deleteModalLabel" style="color: black;">Error al eliminar!</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body" style="color: black;">
                            No se puede eliminar esta categoría. Necesita existir al menos una categoría.
                        </div>
                    {% else %}
                        <div class="modal-header" style="color: black;">
                            <h5 class="modal-title" id="deleteModalLabel" style="color: black;">Eliminar</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body" style="color: black;">
                            ¿Estás seguro de que quieres borrar esta categoría?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                            <a href="{% url 'category_delete' pk=category.pk name=category.name|slugify %}" class="btn btn-danger">Confirmar</a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>

        <!-- Mostrar los posts de la categoría -->
        <h3 class="mt-5">Posts en esta categoría:</h3>
        <div class="row row-cols-1 row-cols-md-2 g-4">
            {% for post in posts %}
            <a href="{% url 'post' post.pk post.category.name|slugify post.date_posted|date:'m' post.date_posted|date:'Y' post.title|slugify %}" class="card-link">
                <div class="card mb-3 w-100 card-hover position-relative">
                    <div class="row g-0">
                        <!-- Conditionally show the image column only if there's a thumbnail -->
                        {% if post.thumbnail %}
                        <div class="col-md-3">
                            <div class="thumbnail-container">
                                <img src="{{ post.thumbnail.url }}" class="img-fluid rounded-start thumbnail-img" alt="{{ post.title }}">
                            </div>
                        </div>
                        <div class="col-md-9"> <!-- 9-column content when thumbnail exists -->
                        {% else %}
                        <div class="col-md-12"> <!-- Full width content when no thumbnail -->
                        {% endif %}
                            <div class="card-body">
                                <div>
                                    <h4 class="card-title post-title">{{ post.title }}</h4>
                                    <p class="card-text post-summary">— {{ post.summary }}</p>
                                </div>
                                <div class="post-extra-info d-flex align-items-center mt-auto">
                                    <!-- Author's profile picture -->
                                    <div class="d-flex align-items-center">
                                        {% if post.author.pfp %}
                                            <img src="{{ post.author.pfp.url }}" alt="{{ post.author.first_name }}" class="profile-picture rounded-circle me-2">
                                        {% else %}
                                            <img src="https://storage.googleapis.com/bucket-weblio/media/profile_pictures/default_pfp.jpg" alt="{{ post.author.first_name }}" class="profile-picture rounded-circle me-2">
                                        {% endif %}
                                        <!-- Author's name and category -->
                                        <span class="text-muted">
                                            <strong>{{ post.author.first_name }} {{ post.author.last_name }}</strong> en <strong>{{ post.category }}</strong>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
            {% empty %}
                <p>No hay posts publicados en esta categoría.</p>
            {% endfor %}
        </div>

        <!-- Formulario separado para Stripe -->
        {% if category.kind == 'premium' and user.is_authenticated and category not in request.user.purchased_categories.all and perms.posts.view_post and not DEBUG %}
            <form action="{% url 'stripe_checkout' category.pk %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-success mt-4">Comprar por {{ category.price }} USD</button>
            </form>
        {% endif %}

    </main>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'));
        var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
            return new bootstrap.Tooltip(tooltipTriggerEl);
        });
    });
</script>
<style>
    /* Thumbnail and Profile Picture Styles */
    .thumbnail-container {
        width: 100%;
        padding-top: 100%; /* 1:1 Aspect Ratio */
        position: relative;
    }
    
    .thumbnail-img {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        object-fit: cover;
    }
    
    /* Profile Picture Styling */
    .profile-picture {
        width: 35px;
        height: 35px;
        object-fit: cover;
    }
    
    /* Card body layout */
    .card-body {
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        height: 100%;
    }
    
    /* Title styling */
    .post-title {
        font-size: 1.5rem;
        color: #007bff;
        margin-bottom: 0.5rem;
    }
    
    /* Summary styling */
    .post-summary {
        font-size: 1.1rem;
        color: #495057;
        margin-bottom: 1rem;
        line-height: 1.5;
    }
    
    /* Extra info section */
    .post-extra-info {
        display: flex;
        align-items: center;
        font-size: 0.9rem;
        color: #6c757d;
        margin-top: auto;
    }
    
    .post-extra-info img {
        margin-right: 10px;
    }
    
    /* Hover effect to enlarge the card */
    .card-hover {
        transition: transform 0.3s ease;
    }
    
    .card-hover:hover {
        transform: scale(1.05); /* Slightly enlarge the card on hover */
    }
    
    /* Make the entire card clickable */
    .card-link {
        text-decoration: none;
        color: inherit;
    }
    
    .card-link:hover .post-title {
        color: #007bff; /* Blue on hover */
        text-decoration: underline;
    }
    
    /* Center the title and content */
    h1 {
        text-align: center;
    }
    
    .container {
        max-width: 1000px; /* Restrict the container's max width to center the content */
        margin: 0 auto; /* Center the container */
    }
    
    .badge-container {
        z-index: 1;
    }
</style>
{% endblock %}

posts/templates/categories/category_add.html
{% extends "base.html" %}
{% block content %}
    <main role="main" class="container py-4">
        <h2>Crear categoria</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Guardar</button>
        </form>

        <script>
            document.addEventListener('DOMContentLoaded', function() {
                const kindSelect = document.getElementById('id_kind');
                const priceInput = document.getElementById('id_price');

                function togglePriceInput() {
                    if (kindSelect.value === 'premium') {
                        priceInput.removeAttribute('readonly');
                    } else {
                        priceInput.setAttribute('readonly', 'readonly');
                        priceInput.value = '0.00'; // Clear the price input when not premium
                    }
                }

                // Initial check
                togglePriceInput();

                // Add event listener
                kindSelect.addEventListener('change', togglePriceInput);

                togglePriceInput();

            });
        </script>
    </main>
{% endblock %}